### ISSUE TITLE
pargraph: getting startes

### ISSUE THREAD

**Issue by Antwnina** [versae/neo4j-rest-client#134]
hello when i entered 
>>> from neo4jrestclient.client import GraphDatabase
>>> gdb = GraphDatabase("http://localhost:7474/db/data/")
There are the following errors how can i resolve them?
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/client.py", line 79, in __init__
    response = Request(**self._auth).get(self.url)
  File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/request.py", line 63, in get
    return self._request('GET', url, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/neo4jrestclient/request.py", line 200, in _request
    raise StatusException(401, "Authorization Required")
neo4jrestclient.exceptions.StatusException: Code [401]: Unauthorized. No permission -- see authorization schemes.
Authorization Required

**Comment by versae** [comment]
Hi, unfortunately `neo4jrestclient` does not support the new Neo4j authorization. The only option so far is to disable it in the Neo4j config until I get the time to implemente it.
